### ISSUE TITLE
New pre-release version of package

### ISSUE THREAD

**Issue by pionl** [vojtasvoboda/oc-smartemailing-plugin#1]
Hi @vojtasvoboda 

could you check this beta version and confirm that everything is ok at your end?

Thank you

https://github.com/pionl/smart-emailing-v3/issues/18

**Comment by vojtasvoboda** [comment]
Hi @pionl, updated to v0.4.1 and tested on production. I'm sorry for not getting back to you sooner.

**Comment by pionl** [comment]
No worries @vojtasvoboda , thank you your time and have a good day!
